---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/register":
    post:
      summary: register user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/login":
    post:
      summary: login user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
